# =================================================================
# Mosquitto Access Control List (ACL)
# =================================================================

# 1. Telemetria Geral
topic readwrite tub/telemetry

# 2. Despacho Operacional - Spring Boot Backend
topic write tub/dispatch/#
topic read tub/dispatch/+/ack

# 3. Despacho Operacional - Consola Motorista (CM) / Autocarros
topic read tub/dispatch/+
topic write tub/dispatch/+/ack
