# ==========================================
# CONFIGURAÇÃO DO SERVIDOR
# ==========================================
server.port=8081

# ==========================================
# 1. LIGAÇÃO À DATA WAREHOUSE
# ==========================================
spring.datasource.url=jdbc:postgresql://localhost:5432/pgu_history
spring.datasource.username=pgu_admin
spring.datasource.password=pgu_password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ==========================================
# 2. SEGURANÇA E ZERO TRUST (KEYCLOAK)
# ==========================================
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/pgu_realm

# ==========================================
# 3. LIGAÇÃO AO BROKER IoT (MOSQUITTO)
# ==========================================
mqtt.broker.url=tcp://localhost:1883
mqtt.client.id=pgu-backend-spring-boot
mqtt.topics.telemetry=tub/telemetry/#
