# ==========================================
# CONFIGURAÇÃO DO SERVIDOR
# ==========================================
server.port=8081

# ==========================================
# 1. LIGAÇÃO À DATA WAREHOUSE
# ==========================================
spring.datasource.url=jdbc:postgresql://datawarehouse:5432/pgu_datawarehouse
spring.datasource.username=${DW_USER}
spring.datasource.password=${DW_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

# ==========================================
# 2. FLYWAY (Migrações da Data Warehouse)
# ==========================================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# ==========================================
# 3. SEGURANÇA E ZERO TRUST (KEYCLOAK)
# ==========================================
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/pgu-realm
